# Generated by Django 3.2.3 on 2021-06-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(default=None, verbose_name='Опубликовано'),
        ),
    ]
