# Generated by Django 3.2.3 on 2021-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_slider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='alt',
            field=models.CharField(blank=True, max_length=180, verbose_name='Сео заголовок'),
        ),
    ]
